# Generated by Django 3.1.3 on 2024-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/img/avatar.png', null=True, upload_to='customer/avatar'),
        ),
    ]
