# Generated by Django 3.1.3 on 2024-06-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240626_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='customer/avatar'),
        ),
    ]
